# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/refs/heads/main/configuration-schema.json
package: wheniwork
output: api.gen.go
generate:
  models: true
  client: true
